### ISSUE TITLE
Remove automatic scrolling through renders

### ISSUE THREAD

**Issue by olopaxx** [noudadrichem/keycapsets.com#106]
Sometimes it gets a little bit annoying when you are trying to look at a keycap set and it automatically scrolls to the next render

**Comment by noudadrichem** [comment]
It should stop when you have your mouse on top of it. If that's not the case please let me know.

**Comment by olopaxx** [comment]
It doesn't stop when im hovering over it, I'm using firefox btw

**Comment by barnumbirr** [comment]
Confirmed on my end (Firefox 84.0.2), render srolling doesn't stop on hover.

**Comment by noudadrichem** [comment]
This is going to be fixed in the next release. Thanks for reporting the issue!
