### ISSUE TITLE
Reddit login no longer works

### ISSUE THREAD

**Issue by barnumbirr** [noudadrichem/keycapsets.com#110]
Hello,

logging into keycapsets.com via Reddit no longer seems to work.

### What I did
Go to keycapsets.com, click on `Login` and select `Login via Reddit`.

### What I expected to happen
Be logged in to my keycapsets.com via Reddit.

### What happened instead
After being redirected to reddit.com to allow keycapsets.com to connect to my Reddit account, the browser redirect to `https://keycapsets.com/sign-up/reddit#access_token=[token_here]&token_type=bearer&state=kcs&expires_in=3600&scope=identity` then hangs.

![Screenshot from 2021-01-14 11-08-40](https://user-images.githubusercontent.com/2029239/104578526-218f8a80-565b-11eb-87fd-2946fb7eead9.png)

Trying to access keycapsets.com after the b0rked login attempt result in the following:

![Screenshot from 2021-01-14 11-09-48](https://user-images.githubusercontent.com/2029239/104578638-4257e000-565b-11eb-911b-a936764d91d9.png)

### Additional info
- running on Firefox 84.0.2 on both Linux and Windows, haven't tried other browsers

Let me know if I can help debug this further. Thank you for creating keycapsets.com. :tada: 
Cheers.

**Comment by noudadrichem** [comment]
Haven't commented on this issue because it works on my end. Also. Your account _IS_ created. Not sure what is happening on your end. Do you have any plugins/extensions that could trouble this?

**Comment by barnumbirr** [comment]
I know my account was created as it used to work just fine. I've just tried disabling all my add-ons, makes no difference unfortunately.

**Comment by noudadrichem** [comment]
So you're saying it's still not working..?

**Comment by barnumbirr** [comment]
Yep, tested again about half an hour ago.

**Comment by noudadrichem** [comment]
I'll investigate. Thanks for reporting!

**Comment by barnumbirr** [comment]
No worries. Thank you for your work ;)
