### ISSUE TITLE
Keyset Upload Validation Ideas

### ISSUE THREAD

**Issue by trevorkirpaul** [noudadrichem/keycapsets.com#18]
I saw #16 but this ticket is more about ideas for how to go forward with the feature.

- IMO there aren't enough keysets to where it would be a bother for a few ppl to manually review.

- You should implement google oauth at the very least and lock `CREATE_KEYSET_MUTATION` down to only registered users. It doesn't take too long to register using google and if a user doesn't have the time to take those few seconds then they're a bad actor, either intentionally or not.

- Your API should sanitize the uploaded URLs from the form, like `websiteUrlValue` or anything else which you directly render in anchor tags

- Form Validation will be a lot easier with a library like [this](https://react-hook-form.com/), in fact your form components will be a lot more simple with that or formik, or any lib of your choosing. I don't think Next.js will have an issue with this tho I personally don't have much exp with SSR.

**Comment by QuadDepo** [comment]
> * You should implement google OAuth at the very least and lock `CREATE_KEYSET_MUTATION` down to only registered users. It doesn't take too long to register using google and if a user doesn't have the time to take those few seconds then they're a bad actor, either intentionally or not.

I would ideally recommend a Reddit OAuth, as the username is quite easy to recognize. Another idea I had was where users could claim sets that they have designed and the same goes for vendors. The only problem is that the username of Reddit and Geekhack might not match and could be confusing and so far I know we can't easily validate geekhack-Reddit users

**Comment by trevorkirpaul** [comment]
> Another idea I had was where users could claim sets that they have designed

That's def a great feature and the concerns with validating accounts are also pretty valid!

In this context, any oauth or even standard user registration is fine, is mainly a small deterrent and gives us a way to lock down the mutation from unregistered users.

At least since you're using gql, it won't be difficult to add an `isActive` or similar property to keysets and leverage that with the query to only fetch the data you want to deliver to the client.

**Comment by Void2258** [comment]
I second the idea of having a manual review before going public. While this involves some work by moderators, it's really the only way to go. No automated system will be able to tell if a picture is of keycaps, authenticating by originating address can be spoofed, and even though OAuth is a good plan, this too can be spoofed if someone is determined enough.

**Comment by QuadDepo** [comment]
I do agree there should be a way to moderate the sets as there is currently none available. Another suggestion would be so set a 10 set/hour limit on all or newer users.

**Comment by noudadrichem** [comment]
What @Void2258 is telling is true. Also @trevorkirpaul valid points on authentication. We're working on a way to authenticate users. The `isActive` stuff is already there so that made it easy to delete all 'sh**t' content. 
What @QuadDepo is saying with the lock for 'new' users could also be an issue. 
We'll fix this all!

We're also thinking about tasks to go public so you could work on them. You sound eager to contribute, and that's nice! @trevorkirpaul

**Comment by noudadrichem** [comment]
Another idea I had is to verify the first set that is added by a designer/vendor when they made an account. after e.g. 1 or 2 verifications the designer is free to upload ICs etc. them selfs. This makes a balance between moderation and trust in vendors/designers. Let me know what you guys think!

**Comment by trevorkirpaul** [comment]
That sounds like a good idea for a "verified" account but perhaps it's safer to lean towards always moderating new uploads and future edits? It's definitely a tricky feature

**Comment by noudadrichem** [comment]
Yeay we're starting with that obviously! haha. Just sharing my own thoughts on here!

**Comment by noudadrichem** [comment]
You can test creating an account on https://testing.keycapsets.com/
Upload keyset is not yet available.

**Comment by noudadrichem** [comment]
Closed this as this is a WIP still.
