### ISSUE TITLE
Contributing Guidelines + prettierrc

### ISSUE THREAD

**Issue by trevorkirpaul** [noudadrichem/keycapsets.com#20]
## Guidelines

Would it benefit this project if there were explicit guidelines on how to contribute?

Here are the [RoR guildelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md) as an example.

## prettierrc

I don't want to create too many tickets but I also don't want to consolidate too many questions.

I've already noticed that PRs have inconsistencies with formatting. You might want to consider adding a [prettier config](https://prettier.io/docs/en/configuration.html) with whatever rules you want.

You can also use eslint. That would be a little more effort but will give you more control.

It might also help if you add vscode project settings to the repo or at least to the `CONTRIBUTING.md`. You should note any conflicting rules that could exist in the developer's user settings.

**Comment by noudadrichem** [comment]
Hi @trevorkirpaul,

We're working on this. It's gonna be there in the near future. tyvm.

**Comment by noudadrichem** [comment]
There is a prettier config and dev setup in the readme.
