### ISSUE TITLE
User account with owned sets, notifications for upcoming

### ISSUE THREAD

**Issue by bbodien** [noudadrichem/keycapsets.com#27]
This seems like an obvious step and might already be planned. 

- Allow users to register, and add sets to a list of sets that they own
- Add a notification mechanism to notify users when a GB goes live, and is ~3 days before its end date

**Comment by noudadrichem** [comment]
We're already working on this. 
This is also discussed in #18 please continue your ideas there. 😊

**Comment by noudadrichem** [comment]
You can test sign-up on https://testing.keycapsets.com/
