### ISSUE TITLE
Move globalState to a hook

### ISSUE THREAD

**Issue by grantglidewell** [noudadrichem/keycapsets.com#36]
Currently, `globalState` is just a state object in `index`. `index` responsible for updating state, fetching new sets, and handling loading states. This is a lot, and confusing.

Proposed solution:
globalState should be a hook in and of itself.

using this hook would look like this:
```js
const { globalState: {filteredKeysets) , setGlobalState, refetch } = useGlobalState()
```

I think it may be worthwhile to also expose a way to trigger a refetch, so that can happen as a result of the last item in the list being in the viewport. 

This moves a lot of logic out of a component, and into a place where it can be extended for further filtering, fetching, and so forth.

**Comment by noudadrichem** [comment]
I completely agree with this. It should be possible to also handle certain global stuff inside a layout. So that every page has access to it.

**Comment by noudadrichem** [comment]
⬆ Resolved.
We now handle state in every component via:
`import { context } from '../context';`
`const { state, dispatch } = useContext<Context>(context);`
