### ISSUE TITLE
Ability to zoom images on a single keycapset page by clicking them.

### ISSUE THREAD

**Issue by noudadrichem** [noudadrichem/keycapsets.com#40]
Every `<img>` tag should be clickable to make it scale to `100vw`. This would make previewing easier.

**Comment by nickbrinser** [comment]
So is the goal to add an actual zoom or to simply expand the selected preview image?

**Comment by noudadrichem** [comment]
https://user-images.githubusercontent.com/16288476/118038619-a2436680-b36f-11eb-8283-3a246b187453.mov

Works!
