### ISSUE TITLE
Implement new keycapset card design.

### ISSUE THREAD

**Issue by noudadrichem** [noudadrichem/keycapsets.com#42]
To make the cards more explanatory we edited the design of the `imageCard` component. This is the new design: 

![image](https://user-images.githubusercontent.com/16288476/80864825-7cc44d00-8c85-11ea-96a5-74baaee759f5.png)

where the color of the duration tags in different for in GB, awaiting GB and IC.

**Comment by rafaeldatarock** [comment]
On it!

**Comment by rafaeldatarock** [comment]
(feature/new-imagecard-design)
