### ISSUE TITLE
Favorites not Removable

### ISSUE THREAD

**Issue by Conman1161** [noudadrichem/keycapsets.com#51]
By clicking on the heart again, you cannot remove favorites. I cannot see a different way that favorites could be removed, so I assume this was the intended method.

**Comment by noudadrichem** [comment]
Yes, I'm fixing this asap. The idea is to make the heart icon a toggle. Kind of like the Instagram behaviour.

**Comment by mvkoto** [comment]
Yep, as of this timestamp favorites not removable

**Comment by noudadrichem** [comment]
I'll update the issue when it's available. No need to add timestamps. 😝

**Comment by noudadrichem** [comment]
This is currently fixed in Testing.
