### ISSUE TITLE
Repeating sets and missing sets when using Availability filters

### ISSUE THREAD

**Issue by Conman1161** [noudadrichem/keycapsets.com#52]
Some sets appear multiple times when using the Availability filters and a majority of sets don't appear when using these filters. I have included pictures for each filter where I found an issue, all after I scrolled down as far as I could and gave ample time to load more sets. All pictures were taken from the test site, but I was able to reproduce all issues on the main site.

**Interest Check:**
![image](https://user-images.githubusercontent.com/56032728/82917621-43f05e80-9f39-11ea-8731-0314eaf9ba05.png)

**Awaiting Groupbuy:**
![image](https://user-images.githubusercontent.com/56032728/82916434-a8aab980-9f37-11ea-8f63-8659b911f46b.png)
![image](https://user-images.githubusercontent.com/56032728/82917433-068bd100-9f39-11ea-90d5-83506102b96c.png)

**In Groupbuy:**
![image](https://user-images.githubusercontent.com/56032728/82916704-fe7f6180-9f37-11ea-9cf0-65074e02ba39.png)
![image](https://user-images.githubusercontent.com/56032728/82918020-c24d0080-9f39-11ea-9311-f1a185cd66f3.png)

**Groupbuy Ended:**
![image](https://user-images.githubusercontent.com/56032728/82917923-a8132280-9f39-11ea-9ae5-4ddb79dcc8c8.png)

**Comment by noudadrichem** [comment]
This is happening in production as well :(

**Comment by noudadrichem** [comment]
This should be fixed now, do you mind testing this for a bit?
I completely rebuild the filters on the API.

**Comment by Conman1161** [comment]
I just went on the test site and still had both issues. Using Opera GX Core: 68.0.3618.142 on Win 10 Pro 64-bit.

![image](https://user-images.githubusercontent.com/56032728/83981105-92f6a600-a8e0-11ea-9046-c6998cf1a44b.png)
![image](https://user-images.githubusercontent.com/56032728/83981106-968a2d00-a8e0-11ea-8835-75d16f27be80.png)
![image](https://user-images.githubusercontent.com/56032728/83981107-98ec8700-a8e0-11ea-9228-b8b5fad8b71f.png)
![image](https://user-images.githubusercontent.com/56032728/83981108-9e49d180-a8e0-11ea-92a1-1850bf1cfdbc.png)
