### ISSUE TITLE
Constant error trying to load keycap sets 

### ISSUE THREAD

**Issue by Halition** [noudadrichem/keycapsets.com#61]
When I click on certain sets (specifically Infinikey 808 Boom, GMK Red Devils, and possibly others I haven't tested yet), it keeps asking me to refresh while never loading the page. 
![image](https://user-images.githubusercontent.com/66137164/83292658-7bb90980-a1b8-11ea-8683-c2b110ce9e23.png)

(Also, I'm new to GitHub so someone tell me if I'm doing this wrong)

**Comment by noudadrichem** [comment]
He, Thanks you're doing well! haha.
I encountered this issue as well as far as I know I already fixed this. Do you mind doing a cache refresh?  This can be done with `shift + ctrl + r`. If it's not fixed do you mind sending the console output?

**Comment by Halition** [comment]
Shift + Ctrl + R doesn't help; I also don't know where to find the console output.

**Comment by noudadrichem** [comment]
It's fine. I know the issue! It's fixed on production. Will update testing Tommorow!
