### ISSUE TITLE
Bug where 'groupbuy ended' tag is one day to early.

### ISSUE THREAD

**Issue by noudadrichem** [noudadrichem/keycapsets.com#64]

**Comment by barnumbirr** [comment]
Hello,
it seems the `Groupbuy Ended` (and `In Groupbuy`) tags is now just broken:

![image](https://user-images.githubusercontent.com/2029239/83696233-36536c80-a5fc-11ea-9af9-df8b9b0176c8.png)

Cheers.

**Comment by noudadrichem** [comment]
Yes.. don't know why. It's mentioned in #52 as well. 😅

**Comment by barnumbirr** [comment]
Ah, my bad. I seem to have missed it.

**Comment by noudadrichem** [comment]
Your mentioned bug is fixed. See #52

**Comment by barnumbirr** [comment]
Well done. 🎉
