### ISSUE TITLE
Drop down menus not showing backgrounds in dark mode

### ISSUE THREAD

**Issue by Halition** [noudadrichem/keycapsets.com#68]
After loading the testing site, all three drop down menus have no backgrounds. 
![image](https://user-images.githubusercontent.com/66137164/85057544-e4b7ef80-b16e-11ea-8e86-3bb7c22adb24.png)

**Comment by noudadrichem** [comment]
I refactored some of the dark mode a while back! Take a look: https://keycapsets.com/
